name: resume_app
description: "My resume mobile application, developped using Flutter."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  country_flags: ^2.2.0
  cupertino_icons: ^1.0.6
  ionicons: ^0.2.2
  flutter_devicon: ^1.0.1
  hidden_drawer_menu: ^3.0.1
  rive: ^0.13.1
  flutter_svg: ^2.0.10+1
  flutter_pdfview: ^1.0.4
  http: ^1.2.0
  url_launcher: ^6.0.12
  file_picker: ^8.0.0+1
  path: ^1.7.0
  path_provider: ^2.1.3
  pdfx: ^2.6.0
  animated_emoji: ^3.1.0
  flutter_gradient_colors: ^2.1.1
  provider: any
  reactive_theme: ^2.1.0
  flutter_map:
  latlong2:
  flutter_localizations:
    sdk: flutter
  intl:
  # localization_i18n_arb:
  # flutter_gen:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/me.jpg
    - assets/riveAssets/
    - assets/appytoons/moody/
    - assets/appytoons/comic/
    - assets/appytoons/halloween/
    - assets/appytoons/illustrations/
    - assets/appytoons/mdf/
    - assets/appytoons/paintings/
    - assets/appytoons/wallpapers/
    - assets/tools/
    - assets/screenshots/
# fonts:
#   family: PlayfairDisplay
#   fonts:
#     - asset: fonts/PlayfairDisplay-Medium.ttf
#       weight: 500
#     - asset: fonts/PlayfairDisplay-MediumItalic.ttf
#       weight: 500
